[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && pip install -r api/requirements.txt"

[deploy]
startCommand = "cd api && PYTHONPATH=/app python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[build.env]
PYTHONPATH = "/app"