[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd api && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300

[build.env]
PYTHONPATH = "/app"