[server]
headless = true
enableCORS = true
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#00f5ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[runner]
magicEnabled = true

# Configuration for multipage apps
[client]
showErrorDetails = true
